#
# NOC & WIRED CONFIGURATION
#
mesh_dim_x: 4
mesh_dim_y: 4
buffer_depth: 4
flit_size: 32
r2h_link_length: 2.0
r2r_link_length: 1.0

# Routing algorithms:
#   XY
#   WEST_FIRST
#   NORTH_LAST
#   NEGATIVE_FIRST
#   ODD_EVEN
#   DYAD
#   TABLE_BASED
routing_algorithm: XY
routing_table_filename: ""

# Routing specific parameters
#   dyad_threshold: double
dyad_threshold: 0.6

# Selection Strategies:
#   RANDOM
#   BUFFER_LEVEL
#   NOP
selection_strategy: RANDOM

#
# WIRELESS CONFIGURATION
#
Hubs:
    defaults:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: []
        toTileBufferSize: 4
        fromTileBufferSize: 4
        rxBufferSize: 4
        txBufferSize: 4

    0:
        attachedNodes: [0,1,4,5]

    1:
        attachedNodes: [2,3,6,7]

    2:
        attachedNodes: [8,9,12,13]

    3:
        attachedNodes: [10,11,14,15]

Channels:
    defaults:
        dataRate: 16
        ber: [0, 0]
        #[TOKEN_PACKET]
        #[TOKEN_HOLD, num_hold_cycles]
        #[TOKEN_MAX_HOLD, max_hold_cycles]
        mac_policy: [TOKEN_PACKET]

    0:
        dataRate: 8

#
# SIMULATION PARAMETERS
#
clock_period_ps: 1000
reset_time: 1000
simulation_time: 10000
stats_warm_up_time: 1000
detailed: false
max_volume_to_be_drained: 0
show_buffer_stats: false

# Winoc
use_winoc: false
use_wirxsleep: false

# Verbosity level:
#   VERBOSE_OFF
#   VERBOSE_LOW
#   VERBOSE_MEDIUM
#   VERBOSE_HIGH
verbose_mode: VERBOSE_OFF

# Trace
trace_mode: false
trace_filename: ""

min_packet_size: 8
max_packet_size: 8
packet_injection_rate: 0.01
probability_of_retransmission: 0.01

# Traffic distribution:
#   TRAFFIC_RANDOM
#   TRAFFIC_TRANSPOSE1
#   TRAFFIC_TRANSPOSE2
#   TRAFFIC_HOTSPOT
#   TRAFFIC_TABLE_BASED
#   TRAFFIC_BIT_REVERSAL
#   TRAFFIC_SHUFFLE
#   TRAFFIC_BUTTERFLY
traffic_distribution: TRAFFIC_RANDOM
traffic_table_filename: "t.txt"


Energy:
    Buffer: #Energy consumed by a single flit in Joule
    #   - [Depth ItemSize Leakage Push Front Pop]
        - [2, 16, 2.05e-4, 3.13e-13, 0,  1.86e-13]
        - [2, 32, 1.35e-3, 6.12e-13, 0,  3.65e-13]
        - [2, 64, 2.68e-3, 1.21e-12, 0,  7.23e-13]
        - [4, 16, 1.16e-3, 3.93e-13, 0,  2.82e-13]
        - [4, 32, 2.27e-3, 7.62e-13, 0,  5.34e-13]
        - [4, 64, 4.48e-3, 1.50e-12, 0,  1.03e-12]
        - [8, 16, 2.08e-3, 5.36e-13, 0,  4.47e-13]
        - [8, 32, 2.30e-3, 1.03e-12, 0,  8.26e-13]
        - [8, 64, 7.91e-3, 2.08e-12, 0,  1.58e-12]

    # Energy(J) for a single bitline. Total flit energy will 
    # be obtained  as flit_size x reported Energy.
    LinkBitLine:
    #   - [ Length (mm), Leakage, Dynamic ] 
        - [0.5, 4.76e-7, 2.50e-14]
        - [1.0, 4.80e-7, 4.88e-14]
        - [1.5, 4.92e-7, 7.25e-14]
        - [2.0, 5.10e-7, 9.63e-14]
        - [2.5, 5.50e-7, 1.20e-13]
        - [3.0, 5.53e-7, 1.43e-13]

    Router:
        # [Static, Dynamic]
        crossbar:
        #   - [I/O Port number, FlitSize, Leakage, Dynamic]
            - [5, 16, 3.78e-4, 1.20e-13]
            - [5, 32, 7.49e-4, 2.21e-13]
            - [5, 64, 1.49e-3, 4.00e-13]

        network_interface:
        #   - [FlitSize, Static, Dynamic]
            - [16, 4.43e-4, 2.50e-13]
            - [32, 8.64e-4, 4.22e-13]
            - [64, 1.72e-3, 8.35e-13]

        routing:
        #   Algorithm:   [Static, Dynamic]
            default:     [1.20e-4, 6.00e-14]
            XY:          [1.20e-4, 6.00e-14]
            WEST_FIRST:  [1.22e-4, 6.05e-14]
            NORTH_LAST:  [1.22e-4, 6.05e-14]
            NEGATIVE_FIRST: [1.22e-4, 6.05e-14]
            ODD_EVEN:    [1.24e-4, 6.10e-14]
            DYAD:        [1.25e-4, 6.23e-14]

        selection:
        #   Strategy:    [Static, Dynamic]
            default:     [1.10e-4, 5.00e-14]
            random:      [6.00e-7, 1.00e-16]
            bufferlevel: [1.00e-6, 2.00e-16]
            nop:         [6.00e-6, 3.00e-16]

    Hub:
        # [RX, TX] Contribution (W)
        transceiver_leakage: [4.43e-4, 1.10e-4]

        # [RX, TX] Contribution (W)
        transceiver_biasing: [1.5e-2, 7e-3]

        # RX Dynamic Contribution in J/bit (RX Digital Interfaces)
        rx_dynamic: 7e-13

        # in W
        rx_snooping: 1.0e-15

        # TX Dynamic Contribution in W (To be divided for Datarate)
        default_tx_energy: 1e-2

        tx_attenuation_map:
        #   - [TX Hub ID, RX Hub ID, Attenuation]
            - [0, 1, 1.1]
            - [0, 2, 2.2]
            - [0, 3, 3.3]
            - [1, 0, 1.0]
            - [1, 2, 2.2]
            - [1, 3, 3.3]
            - [2, 0, 1.0]
            - [2, 1, 1.1]
            - [2, 3, 3.3]
            - [3, 0, 1.0]
            - [3, 1, 1.1]
            - [3, 2, 2.2]
